# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: 3dgs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)
_sym_db = _symbol_database.Default()
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\n3dgs.proto\x12\x06qcraft\"\xa3\x01\n\x0bMainCarInfo\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\x0c\n\x04roll\x18\x04 \x01(\x01\x12\r\n\x05pitch\x18\x05 \x01(\x01\x12\x0b\n\x03yaw\x18\x06 \x01(\x01\x12\x11\n\tsensor_id\x18\x07 \x01(\t\x12\x11\n\ttimestamp\x18\x08 \x01(\x01\x12\x0e\n\x06sha256\x18\t \x01(\t\x12\x13\n\x0bsensor_data\x18\n \x01(\x0c')
_MAINCARINFO = DESCRIPTOR.message_types_by_name['MainCarInfo']
MainCarInfo = _reflection.GeneratedProtocolMessageType('MainCarInfo', (_message.Message,), {
  'DESCRIPTOR' : _MAINCARINFO,
  '__module__' : '3dgs_pb2'
  # @@protoc_insertion_point(class_scope:qcraft.MainCarInfo)
  })
_sym_db.RegisterMessage(MainCarInfo)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _MAINCARINFO._serialized_start=23
  _MAINCARINFO._serialized_end=186
# @@protoc_insertion_point(module_scope)