# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Pose.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nPose.proto\"\xc9\x01\n\x0bMainCarInfo\x12\x0e\n\x01x\x18\x01 \x01(\x01H\x00\x88\x01\x01\x12\x0e\n\x01y\x18\x02 \x01(\x01H\x01\x88\x01\x01\x12\x0e\n\x01z\x18\x03 \x01(\x01H\x02\x88\x01\x01\x12\x11\n\x04roll\x18\x04 \x01(\x01H\x03\x88\x01\x01\x12\x12\n\x05pitch\x18\x05 \x01(\x01H\x04\x88\x01\x01\x12\x10\n\x03yaw\x18\x06 \x01(\x01H\x05\x88\x01\x01\x12\x16\n\tcamera_id\x18\x07 \x01(\x05H\x06\x88\x01\x01\x42\x04\n\x02_xB\x04\n\x02_yB\x04\n\x02_zB\x07\n\x05_rollB\x08\n\x06_pitchB\x06\n\x04_yawB\x0c\n\n_camera_idb\x06proto3')



_MAINCARINFO = DESCRIPTOR.message_types_by_name['MainCarInfo']
MainCarInfo = _reflection.GeneratedProtocolMessageType('MainCarInfo', (_message.Message,), {
  'DESCRIPTOR' : _MAINCARINFO,
  '__module__' : 'Pose_pb2'
  # @@protoc_insertion_point(class_scope:MainCarInfo)
  })
_sym_db.RegisterMessage(MainCarInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAINCARINFO._serialized_start=15
  _MAINCARINFO._serialized_end=216
# @@protoc_insertion_point(module_scope)
