[global]
index-url = https://pypi.tuna.tsinghua.edu.cn/simple
extra-index-url =
    https://pypi.mirrors.ustc.edu.cn/simple
    https://mirrors.aliyun.com/pypi/simple
    https://mirrors.nju.edu.cn/pypi/web/simple
    https://pypi.org/simple

[install]
trusted-host =
    pypi.tuna.tsinghua.edu.cn
    pypi.mirrors.ustc.edu.cn
    mirrors.aliyun.com
    mirrors.nju.edu.cn
    pypi.org
